require("plugins")
require("config")
require("shorcuts")
require("statusbar")
require("telescope")
require("multiconfig")
require("barbar")
require("dashboard")
require("coc")
require("colors")
require("parentheses")
require("lspServer")
vim.cmd("source ./vimscript/main.vim")
